services:
  frontend:
    build:
      context: ./Frontend
      args:
        - VITE_APP_MODE=operator
        - VITE_BACKEND_URL=http://localhost:8087
    container_name: phoenix_local_frontend
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build: ./Backend
    container_name: phoenix_local_api
    ports:
      - "127.0.0.1:8087:8080"
      - "127.0.0.1:8088:8088"
    environment:
      - AppMode=Operator
      - CommandServerIP=host.docker.internal
      - CommandServerPort=8090
      - CommandKey=123
      - InfluxDBLocal__Url=http://phoenix_influx_local:8086
      - InfluxDBLocal__Token=my-super-secret-local-token
      - InfluxDBLocal__Org=UiSAerospace
      - InfluxDBLocal__Bucket=PhoenixLocal
      - InfluxDBCloud__Url=http://192.168.0.184:8086
      - InfluxDBCloud__Token=my-super-secret-cloud-token
      - InfluxDBCloud__Org=UiSAerospace
      - InfluxDBCloud__Bucket=PhoenixCloud
    depends_on:
      - influxdb
    
  influxdb:
    image: influxdb:2.7.5
    container_name: phoenix_influx_local
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=aerospace123
      - DOCKER_INFLUXDB_INIT_ORG=UiSAerospace
      - DOCKER_INFLUXDB_INIT_BUCKET=PhoenixLocal
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-local-token
    volumes:
      - influxdb-local-data:/var/lib/influxdb2
      - influxdb-local-config:/etc/influxdb2
    restart: unless-stopped

volumes:
  influxdb-local-data:
  influxdb-local-config: