/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 borealis2.gltf --types 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'  
import type { ThreeElements } from '@react-three/fiber' 


type GLTFResult = GLTF & {
  nodes: {
    imagetostl_mesh0_1: THREE.Mesh
    imagetostl_mesh0_2: THREE.Mesh
    imagetostl_mesh0_3: THREE.Mesh
    imagetostl_mesh0_4: THREE.Mesh
    imagetostl_mesh0_5: THREE.Mesh
  }
  materials: {
    mat0: THREE.MeshStandardMaterial
    ['mat0.001']: THREE.MeshStandardMaterial
    ['mat0.002']: THREE.MeshStandardMaterial
    ['mat0.003']: THREE.MeshStandardMaterial
    ['mat0.004']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export default function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/borealis2.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.imagetostl_mesh0_1.geometry} material={materials.mat0} />
      <mesh geometry={nodes.imagetostl_mesh0_2.geometry} material={materials['mat0.001']} />
      <mesh geometry={nodes.imagetostl_mesh0_3.geometry} material={materials['mat0.002']} />
      <mesh geometry={nodes.imagetostl_mesh0_4.geometry} material={materials['mat0.003']} />
      <mesh geometry={nodes.imagetostl_mesh0_5.geometry} material={materials['mat0.004']} />
    </group>
  )
}

useGLTF.preload('/borealis2.gltf')
